# Write your MySQL query statement below
SELECT REQUESTER_ID AS ID, COUNT(ACCEPTER_ID) AS NUM
FROM
((SELECT REQUESTER_ID, ACCEPTER_ID
FROM REQUESTACCEPTED)
UNION ALL
(SELECT ACCEPTER_ID, REQUESTER_ID
FROM REQUESTACCEPTED)) T
GROUP BY REQUESTER_ID
ORDER BY NUM DESC
LIMIT 1