# Write your MySQL query statement below
WITH DATA AS (SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT
FROM CUSTOMER
GROUP BY VISITED_ON)

SELECT D1.VISITED_ON, SUM(D2.AMOUNT) AS AMOUNT, ROUND(AVG(D2.AMOUNT), 2) AS AVERAGE_AMOUNT
FROM DATA D1
LEFT JOIN DATA D2
ON D1.VISITED_ON >= D2.VISITED_ON
WHERE DATEDIFF(D1.VISITED_ON, D2.VISITED_ON) BETWEEN 0 AND 6
AND D1.VISITED_ON >= (SELECT DATE_ADD(MIN(VISITED_ON), INTERVAL 6 DAY) FROM CUSTOMER)
GROUP BY D1.VISITED_ON
ORDER BY D1.VISITED_ON