# Write your MySQL query statement below
SELECT A.CUSTOMER_ID
FROM
(SELECT CUSTOMER_ID, COUNT(DISTINCT PRODUCT_KEY) AS S, PRODUCT_KEY
FROM CUSTOMER
GROUP BY CUSTOMER_ID) A
LEFT JOIN PRODUCT B
ON A.PRODUCT_KEY = B.PRODUCT_KEY
WHERE A.S = (SELECT COUNT(DISTINCT PRODUCT_KEY) FROM PRODUCT);