# Write your MySQL query statement below
SELECT S.PRODUCT_ID, P.FIRST_YEAR, S.QUANTITY, S.PRICE
FROM
(SELECT PRODUCT_ID, MIN(YEAR) AS FIRST_YEAR
FROM SALES
GROUP BY PRODUCT_ID) P
LEFT JOIN SALES S
ON P.PRODUCT_ID = S.PRODUCT_ID
WHERE P.FIRST_YEAR = S.YEAR