# Write your MySQL query statement below
WITH DATA AS (SELECT DISTINCT SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC
LIMIT 1,2)

SELECT IF(COUNT(SALARY) > 0, SALARY, NULL) AS SECONDHIGHESTSALARY
FROM DATA
ORDER BY SALARY