# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E1.NAME AS EMPLOYEE, E1.SALARY AS SALARY
FROM EMPLOYEE E1
LEFT JOIN DEPARTMENT D
ON E1.DEPARTMENTID = D.ID
WHERE (
    SELECT COUNT(DISTINCT E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E1.DEPARTMENTID = E2.DEPARTMENTID
    AND E1.SALARY < E2.SALARY
) < 3