# Write your MySQL query statement below
SELECT ROUND(SUM(IF(DATEDIFF(EVENT_DATE, FIRST_DAY) = 1, 1, 0)) / COUNT(DISTINCT P.PLAYER_ID), 2) AS FRACTION
FROM
(SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_DAY
FROM ACTIVITY
GROUP BY PLAYER_ID) P
LEFT JOIN ACTIVITY A
ON P.PLAYER_ID = A.PLAYER_ID