# Write your MySQL query statement below
WITH DATA AS
(SELECT *, DATEDIFF('2019-08-16', CHANGE_DATE) AS DIFF
FROM PRODUCTS)

SELECT D2.PRODUCT_ID, IFNULL(SUM(D2.PRICE), 10) AS PRICE
FROM
(SELECT DATA.*, D.MIN_DIFF, CASE WHEN DATA.DIFF = D.MIN_DIFF
THEN NEW_PRICE WHEN DATA.DIFF <> D.MIN_DIFF THEN 0 ELSE NULL
END AS PRICE
FROM DATA
LEFT JOIN
(SELECT PRODUCT_ID, MIN(DIFF) AS MIN_DIFF
FROM DATA
WHERE DIFF >= 0
GROUP BY PRODUCT_ID) D
ON DATA.PRODUCT_ID = D.PRODUCT_ID) D2
GROUP BY D2.PRODUCT_ID;