# Write your MySQL query statement below
SELECT ROUND(SUM(IF(F.FIRST_ORDER_DATE = D.CUSTOMER_PREF_DELIVERY_DATE, 1, 0)) / COUNT(*) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY D
LEFT JOIN
(SELECT CUSTOMER_ID, MIN(ORDER_DATE) AS FIRST_ORDER_DATE
FROM DELIVERY
GROUP BY CUSTOMER_ID) F
ON D.CUSTOMER_ID = F.CUSTOMER_ID
WHERE D.ORDER_DATE = F.FIRST_ORDER_DATE