# Write your MySQL query statement below
SELECT A.EMPLOYEE_ID, A.DEPARTMENT_ID
FROM EMPLOYEE A
LEFT JOIN 
(SELECT EMPLOYEE_ID, COUNT(EMPLOYEE_ID) AS C
FROM EMPLOYEE
GROUP BY EMPLOYEE_ID) B
ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
WHERE B.C = 1 OR A.PRIMARY_FLAG = 'Y'