# Write your MySQL query statement below
SELECT RESULTS FROM
(SELECT NAME AS RESULTS
FROM
(SELECT USER_ID, COUNT(MOVIE_ID) AS T
FROM MOVIERATING
GROUP BY USER_ID) T1
INNER JOIN USERS T2
ON T1.USER_ID = T2.USER_ID
ORDER BY T1.T DESC, T2.NAME ASC
LIMIT 1) Q
UNION ALL
SELECT RESULTS FROM
(SELECT Z2.TITLE AS RESULTS
FROM
(SELECT MOVIE_ID, AVG(RATING) AS S
FROM MOVIERATING
WHERE CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY MOVIE_ID) Z1
INNER JOIN MOVIES Z2
ON Z1.MOVIE_ID = Z2.MOVIE_ID
ORDER BY Z1.S DESC, Z2.TITLE
LIMIT 1) P