# Write your MySQL query statement below
SELECT DISTINCT A.NUM AS CONSECUTIVENUMS
FROM LOGS A
LEFT JOIN LOGS B
ON A.ID + 1 = B.ID
LEFT JOIN LOGS C
ON B.ID + 1 = C.ID
WHERE A.NUM = B.NUM
AND B.NUM = C.NUM